project11/platforms/molab:
  robot_description: molab/robot_description
  width: 2.2
  length: 10.0
  reference_x: 0.2
  reference_y: 8.0
  nav_sources:
    ais:
      position_topic: /molab/sensors/ais/fix
      orientation_topic: /molab/sensors/ais/heading
      velocity_topic: /molab/sensors/ais/vel

mru_transform/sensors:
 - name: ais
   topics: { position: 'sensors/ais/fix', orientation: 'sensors/ais/heading', velocity: 'sensors/ais/vel'}
